# Generated by Django 5.1.7 on 2025-03-16 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                (
                    "price",
                    models.FloatField(
                        verbose_name=django.core.validators.MinValueValidator(1.0)
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.IntegerField(
                        verbose_name=django.core.validators.MinValueValidator(0)
                    ),
                ),
            ],
        ),
    ]
